appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: szhf7pHnOYcF6BiAagN5m7viU4VmNQ3TpLzx7cNL+t9Yy12cxTKpsZ8QwmT9gbxq8g5jkBzB3tDMFQYfRgx//5OFBmq4QvosVnJrLO+kibIy4DFXb2C3NAj/cIRY3RVNeyAwfXmTGYsAwsGxqOS7eM1LMh2dvHSjT6YXIOktgGZHheZ/4x5zKWndxDikYGcA1xBj/YgNt7F0/4GCfgbdLSDvHfYpV9I+cRFyA1fxi16GUyeG3rM+WWkiFkCqRByH+2exg5INfgEtaEE/odITk9Xmajij5xBlZY1AItrfKKJiZsN65euOIoEqRqPy1EM22N9GFVe23wlpNYCy/3XWwzDda9swsU1W00ptDRI75RnzgtbGc3Z8p6GvyxSYI8GD+Wf0PGcy+KvNNKiEBfSBpNJd8lvWZjMeah57fzmrWREGtwpgCeOijnLGCJV2Uu+6LMei8PlWG8T+rOtl9eGJl2s3H7a+UENXXjShnaoqSBcGfGmxe3lI3L8qe6iXH2TGcq91bwv+WXhKcmXEZbld/3DP9DeJT2MfTcOFc3m5Zo3Xwy2Py4eR61sajEZBkAPn+oYhjGlbMLg6QfUU3GItLHCqd5vayXKzsDhsFlO5QCRbq9rwLD5Zq9Wj19LlEKKhQozfwncBC39uF0uzJWh4jRiLNvO+B/K1lF+XlPYjEWE=
conda_forge_output_validation: true
